### ISSUE TITLE
Device tracking accurate to each AP

### ISSUE THREAD

**Issue by Resurrection2981** [idatum/unifi_tracker#1]
Hi,
    Is it possible to get the AP name which the device is connected to and using the AP name for room tracking?

**Comment by idatum** [comment]
Ooh interesting. Well, the code already knows the IP address of the AP it's connecting with to get attached clients. That can be returned along with client MAC addresses. You can then resolve the DNS name of the IP address of the AP if you prefer a DNS name over an IP to associate a name with attached clients.

Also -- to avoid DNS -- the utility that the code executes remotely is `mca-dump`. You can ssh into one of your APs and run it, and you'll see the JSON output that includes a hostname value.

It would be a breaking change regarding current HA configuration, but one option is to include either the IP or hostname in the MQTT topic. Then in HA, split the presence detection into separate MQTT topics, one for each AP (i.e. room location). Maybe that can be an option in the example /app/device_tracker.py with support from /src/unifi_tracker.py.

Good idea👍

**Comment by idatum** [comment]
I created a new branch, scan_by_ap, with a new method to group the diff between scans by AP host name. I'll use this branch in my testing with HA to allow presence detection per AP.

**Comment by idatum** [comment]
Addressed with release v.0.1.0.

**Comment by Resurrection2981** [comment]
Great! I'll try it.
Btw, when I add this repo to HACS, it says "<Integration idatum/unifi_tracker> Repository structure for v.0.1.0 is not compliant"
